# Blocker.Pixie.
#
# For customizations, prefer using docker-compose.override.yml.

# config.
version: '3'

# volumes.
volumes:
  # Redis Data.
  redis-data:
  # ipfs data volume.
  ipfs-data:
  # ipfs staging volume.
  ipfs-staging:
  # .config.
  dot-config:
  # .local.
  dot-local:
  # .cache.
  dot-cache:
  # .composer.
  dot-composer:

# services.
services:

  # Redis.
  cache:
    image: redis:4
    container_name: pixie-redis
    command: --appendonly yes --requirepass "pixie"
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: pixie-ipfs
    volumes:
      - ipfs-staging:/export
      - ipfs-data:/data/ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080


  # API.
  pixie:
    image: ambientum/php:7.2
    command: "/var/www/app/start"
    container_name: pixie-api
    environment:
      - FRAMEWORK=laravel-cache
      - XDEBUG_ENABLED=false
      - PHP_IDE_CONFIG=serverName=ambientum
    volumes:
      - .:/var/www/app
      - dot-config:/home/ambientum/.config
      - dot-cache:/home/ambientum/.cache
      - dot-local:/home/ambientum/.local
      - dot-composer:/home/ambientum/.composer
    ports:
      - 80:8080
      - 443:8083
    links:
      - cache
      - ipfs
